spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/currency_db
    url: jdbc:postgresql://db:5432/currency_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    check:
      price:
        value: 2
    notify:
      delay:
        value: 10
    unit: MINUTES
    inactive:
      days: 30

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
